### PR TITLE
Avoid message value factory initialization in Apache Giraph

### PR DESCRIPTION
**Pull request by yukselakinci**
Jira ticket id: https://issues.apache.org/jira/browse/GIRAPH-1151

### CODE REVIEW

**Comment by dlogothetis** [comment]
@yukselakinci, can you add in the description how you tested this.

**Comment by yukselakinci** [comment]
I ran Giraph unit tests, internal unit/snapshot tests, and a production job. Production job ran 10% faster after these changes.

**Comment by dlogothetis** [comment]
Just one last question, is the change in SendOneMessageToManyCache.java exercised by the tests you run? Can we make sure?

**Comment by yukselakinci** [comment]
Yes, I confirmed that It is exercised by internal tests.

**Comment by dlogothetis** [comment]
+1

**Review by aching — APPROVED** [review]

**Pull request closed without merging**
